FROM  centos6:6.8
MAINTAINER  HJ lxxpsp2007@126.com

ADD nginx-1.10.2.tar.gz /usr/local/


EXPOSE 80
ENTRYPOINT [ "/usr/local/nginx-1.10.2/sbin/nginx" ]

#/var/log/nginx/  /etc/nginx/conf/  /data/www/www
